AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating an RDS instance

Parameters:
  DBName:
    Type: String
    Default: file_service
  DBUsername:
    Type: String
    Default: postgres
  DBPassword:
    Type: String
    NoEcho: true

Resources:
  FileServiceDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: postgres
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
